ITensors.op(::OpName"sigma_plus",::SiteType"Qubit") =
 [0 1
  0 0]

ITensors.op(::OpName"sigma_minus",::SiteType"Qubit") =
 [0 0
  1 0]

function kinetic_1d_nn(L, sites) 
    kinetic = OpSum()
    for i in 1:L
        os = OpSum()
        os += 1,"sigma_plus",L-(i-1)
        for i in 1:L-i 
            os *=  ("Id",i) 
        end
        for i in L+2-i :L 
            os *=  ("sigma_minus",i) 
        end
        kinetic += os
    end
    for i in 1:L
        os = OpSum()
        os += 1,"sigma_minus",L-(i-1)
        for i in 1:L-i 
            os *=  ("Id",i) 
        end
        for i in L+2-i :L 
            os *=  ("sigma_plus",i) 
        end
        kinetic += os
    end
    k_mpo = MPO(kinetic,sites)
    return k_mpo 
end

function kinetic_1d_nn_custom(L, sites, hopping) 

    kinetic_1 = OpSum()
    kinetic_2 = OpSum()
    for i in 1:L
        os = OpSum()
        os += 1,"sigma_plus",L-(i-1)

        for i in 1:L-i 
            os *=  ("Id",i) 
        end
        for i in L+2-i :L 
            os *=  ("sigma_minus",i) 
        end
        
        kinetic_1 += os
    end
    k_mpo_1 = MPO(kinetic_1,sites)
    true_hop_1 = apply(hopping, k_mpo_1)

    for i in 1:L
        os = OpSum()
        os += 1,"sigma_minus",L-(i-1)

        for i in 1:L-i 
            os *=  ("Id",i) 
        end


        for i in L+2-i :L 
            os *=  ("sigma_plus",i) 
        end
        
        kinetic_2 += os
    end
 
    k_mpo_2 = MPO(kinetic_2,sites)
    true_hop_2 = apply(k_mpo_2, hopping)
    k_mpo =  +(true_hop_1, true_hop_2;  cutoff = 1e-8)   
    return k_mpo 
end

function custom_mpo(mps,new_sites)
    #input is 2N MPS generated by QTCI, new_sites are the actual sites of the system
    N = length(mps)
    new_N = N ÷ 2
    new_mpo = MPO(new_N)
    
    for i in 1:new_N
        idx1 = 2i - 1
        idx2 = 2i
        
         
        A = mps[idx1]
        B = mps[idx2]
        combined_T = A * B
        
     
        old_s1 = siteind(mps, idx1)
        old_s2 = siteind(mps, idx2)
  
        new_s_in = new_sites[i]'
        new_s_out = new_sites[i]
         
        new_mpo[i] = replaceinds(combined_T, [old_s1, old_s2] => [new_s_in, new_s_out])
    end
    
    return new_mpo
end

function binary_to_MPS(n, size,sites)
    # Convert to binary string
    binary_str = string(n, base=2)
    
    # Pad the binary string with leading zeros to match the desired size
    padded_binary_str = lpad(binary_str, size, '0')
    
    # Convert the padded string into MPS
    return random_mps(sites,collect(padded_binary_str) |> x -> map(s -> string(s), x))
end

